Models/ErrorViewModel.cs
using System;

namespace AppointmentApplication.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Expense.cs
using System.ComponentModel.DataAnnotations;

namespace AppointmentApplication.Models
{
    public class Expense
    {
        public int Id { get; set; }
        [Required]
        public string ExpenseName { get; set; }
        [Required]
        [Range(1.00, 4000, ErrorMessage ="Amount must be greater than 0 and less than 4000")]
        public float Amount { get; set; }
    }
}

Models/Item.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace AppointmentApplication.Models
{
    public class Item
    {
        [Key]
        public int Id { get; set; }

        public string Borrower { get; set; }
        public string Lender { get; set; }

        [DisplayName("Item Name")]
        public string ItemName { get; set; }
    }
}

Controllers/AppointmentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AppointmentApplication.Controllers
{
    public class AppointmentController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/ExpenseController.cs
using AppointmentApplication.Data;
using AppointmentApplication.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace AppointmentApplication.Controllers
{
    public class ExpenseController : Controller
    {
        private readonly ApplicationDbContext dbContext;

        public ExpenseController(ApplicationDbContext db)
        {
            dbContext = db;
        }

        public IActionResult Index()
        {
            //get items from DB
            IEnumerable<Expense> objectList = dbContext.Expenses;
            return View(objectList);
        }

        public IActionResult Create()
        {
            //get items from DB
            //IEnumerable< Item > objectList = _db.Items;
            //return View(objectList);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken] //just if we are logged in
        public IActionResult Create(Expense expense)
        {
            if (ModelState.IsValid)
            {
                //get items from DB
                dbContext.Expenses.Add(expense);
                dbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(expense);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var expense = dbContext.Expenses.Find(id);
            if (expense == null)
            {
                return NotFound();
            }
            //get items from DB
            dbContext.Expenses.Remove(expense);
            dbContext.SaveChanges();
            return RedirectToAction("Index");
        }

        //Get - delete
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //get items from DB
            var expense = dbContext.Expenses.Find(id);
            if (expense == null)
            {
                return NotFound();
            }

            return View(expense);  // return the view with out object so we can display the info we are getting
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult UpdatePost(Expense expense)
        {
            if (ModelState.IsValid)
            {
                //get items from DB
                dbContext.Expenses.Update(expense);
                dbContext.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(expense);
        }

        //Get - update
        public IActionResult Update(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            //get items from DB
            var expense = dbContext.Expenses.Find(id);
            if (expense == null)
            {
                return NotFound();
            }

            return View(expense);  // return the view with out object so we can display the info we are getting
        }
    }
}

Controllers/HomeController.cs
using AppointmentApplication.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace AppointmentApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ItemController.cs
using AppointmentApplication.Data;
using AppointmentApplication.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace AppointmentApplication.Controllers
{
    public class ItemController : Controller
    {
        public ApplicationDbContext _db;
        public ItemController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            //get items from DB
            IEnumerable<Item> objectList = _db.Items;
            return View(objectList);
        }

        public IActionResult Create()
        {
            //get items from DB
            //IEnumerable< Item > objectList = _db.Items;
            //return View(objectList);
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken] //just if we are logged in 
        public IActionResult Create(Item obj)
        {
            //get items from DB
            _db.Items.Add(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Appointment/Index.cshtml
@model IEnumerable<AppointmentApplication.Models.Item>
@{
    ViewData["Title"] = "Index";
}

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Borrow Items List</h2>
        </div>
        <div class="col-6">
            Create Item
        </div>
    </div>
    @if(Model.Count() > 0)
            {

            }
</div>

Views/Expense/Create.cshtml
@model AppointmentApplication.Models.Expense
<form method="post" asp-action="Create">
    <div class="border p-3">
        @*<div asp-validation-summary="All" class="text-danger"></div>*@ 
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Add Item</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="ExpenseName"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Amount"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <input asp-for="ExpenseName" class="form-control" />
                        <span asp-validation-for="ExpenseName" class="text-danger"></span>
                    </div>
                    <div class="col-4">
                        <input asp-for="Amount" class="form-control" />
                        <span asp-validation-for="Amount" class="text-danger"></span>
                    </div>
   
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-danger w-75">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
@*client validation*@
@section Scripts{ 
@{ <partial name="_ValidationScriptsPartial"/>
}
}

Views/Expense/Delete.cshtml
@model AppointmentApplication.Models.Expense
<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden/>
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Delete Expense</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="ExpenseName"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Amount"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <input asp-for="ExpenseName" disabled class="form-control" />
                    </div>
                    <div class="col-4">
                        <input asp-for="Amount" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-danger w-75" value="Delete" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-75">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
@*client validation*@
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Expense/Index.cshtml
@model IEnumerable<AppointmentApplication.Models.Expense>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Expenses List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="Expense" asp-action="Create" class="btn btn-primary">Create new expense</a>
        </div>
    </div>
    <br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Expense Name
                    </th>
                    <th>
                        Amount
                    </th>                    
                    <th>
                        Manage
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var expense in Model)
                {
                    <tr>
                        <td width="35%">@expense.ExpenseName</td>
                        <td width="35%">@expense.Amount</td>
                        <td width="30%">
                            <div class="col-6 w-100 btn-group" role="group">
                                <a asp-controller="Expense" asp-action="Delete" asp-route-Id="@expense.Id" class="btn btn-danger mx-1">Delete</a> @*pass the id to the new page*@
                                <a asp-controller="Expense" asp-action="Update" asp-route-Id="@expense.Id" class="btn btn-primary mx-1">Update</a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No items created yet</p>
    }
</div>

Views/Expense/Update.cshtml
@model AppointmentApplication.Models.Expense
<form method="post" asp-action="UpdatePost">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Update Expense</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="ExpenseName"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Amount"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <input asp-for="ExpenseName" class="form-control" />
                    </div>
                    <div class="col-4">
                        <input asp-for="Amount" class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-success w-75" value="Update" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-info w-75">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
@*client validation*@
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Item/Create.cshtml
@model AppointmentApplication.Models.Item

<form method="post" asp-action="Create">
    <div class="border p-3">
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Add Item</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-4">
                        <label asp-for="ItemName"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Borrower"></label>
                    </div>
                    <div class="col-4">
                        <label asp-for="Lender"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <input asp-for="ItemName" class="form-control" />
                    </div>
                    <div class="col-4">
                        <input asp-for="Borrower" class="form-control" />
                    </div>
                    <div class="col-4">
                        <input asp-for="Lender" class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="create" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-danger w-75">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

Views/Item/Index.cshtml
@model IEnumerable<AppointmentApplication.Models.Item>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">Borrowed Items List</h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="Item" asp-action="Create" class="btn btn-primary">Create new Item</a>
        </div>
    </div>
    <br />

    @if (Model.Count() > 0)
    {
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Item Name
                    </th>
                    <th>
                        Borrower
                    </th>
                    <th>
                        Lender
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td width="30%">@item.ItemName</td>
                        <td width="30%">@item.Borrower</td>
                        <td width="30%">@item.Lender</td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No items created yet</p>
    }

</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppointmentApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AppointmentApplication</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Item" asp-action="Index">Items</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Expense" asp-action="Index">My expenses</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - AppointmentApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>